import {
  contentVersionLine,
  deriveTrustRows,
  humanizeModel,
  identityLine,
} from "@/components/TrustBadge";
import type { TrustManifest } from "@/types/trust";

// deriveTrustRows is the pure manifest→rows mapping behind <TrustBadge>. It owns
// the load-bearing honesty rules from ADR-015 / SBQ-TRUST-001: render only facts
// the manifest carries, never upgrade an unset block to a pass, and never claim
// "verified" for an unverified model. Rendering itself runs in a WebView-free
// RN tree, so the logic — not the layout — is what these tests pin down.

function manifest(overrides: Partial<TrustManifest> = {}): TrustManifest {
  return {
    trust_manifest_version: 1,
    provenance: {
      provider: "anthropic",
      model: "claude-sonnet-4-6",
      model_verified: true,
      contract_version: 1,
    },
    validation: { schema_validated: true, repair_attempts: 0, schema_id: "lesson@1" },
    ...overrides,
  };
}

const row = (rows: ReturnType<typeof deriveTrustRows>, label: string) =>
  rows.find((r) => r.label === label);

describe("deriveTrustRows", () => {
  it("shows an allow-listed model as a pass, with descriptive (non-endorsement) copy", () => {
    const r = row(deriveTrustRows(manifest()), "Generated by")!;
    expect(r.tone).toBe("pass");
    expect(r.glyph).toBe("✓");
    expect(r.value).toContain("allow-listed model"); // ADR-016 D7: not "verified by <provider>"
    expect(r.value).toContain("claude-sonnet-4-6"); // concrete model id present
  });

  it("shows an unverified model honestly and as a note, not a pass (AC4)", () => {
    const rows = deriveTrustRows(
      manifest({
        provenance: { provider: "deepseek", model: "deepseek-chat", model_verified: false },
      }),
    );
    const r = row(rows, "Generated by")!;
    expect(r.tone).toBe("note"); // downgrades the headline — never a green pass
    expect(r.value).toContain("unverified");
    expect(r.value).not.toContain("allow-listed");
  });

  it("marks a clean validation as a plain pass", () => {
    const r = row(deriveTrustRows(manifest()), "Structure check")!;
    expect(r.tone).toBe("pass");
    expect(r.value).toBe("Validated against our lesson template");
  });

  it("flags a repaired generation as auto-corrected but still a pass (AC3)", () => {
    const rows = deriveTrustRows(
      manifest({ validation: { schema_validated: true, repair_attempts: 1 } }),
    );
    const r = row(rows, "Structure check")!;
    expect(r.tone).toBe("pass");
    expect(r.value).toContain("auto-corrected");
  });

  it("omits compliance/integrity rows when the blocks are absent (AC5)", () => {
    const rows = deriveTrustRows(manifest());
    expect(row(rows, "Format checks")).toBeUndefined();
    expect(row(rows, "Integrity")).toBeUndefined();
  });

  it("renders the compliance count when present", () => {
    const rows = deriveTrustRows(
      manifest({
        compliance: {
          ruleset: "mentible-professional@1.0",
          checks_passed: 6,
          checks_total: 6,
          status: "pass",
        },
      }),
    );
    const r = row(rows, "Format checks")!;
    expect(r.tone).toBe("pass");
    expect(r.value).toBe("Passed 6/6 format checks");
  });

  it("treats pass_with_notes compliance as a note, not a failure", () => {
    const rows = deriveTrustRows(
      manifest({
        compliance: {
          ruleset: "mentible-professional@1.0",
          checks_passed: 11,
          checks_total: 13,
          status: "pass_with_notes",
        },
      }),
    );
    const r = row(rows, "Format checks")!;
    expect(r.tone).toBe("note");
    expect(r.glyph).toBe("✓"); // a note, but not the ⚠ reserved for a hard fail
  });

  it("distinguishes reviewer-not-author from a plain human approval (SoD)", () => {
    const withSoD = row(
      deriveTrustRows(
        manifest({ review: { human_approved: true, approver_distinct_from_generator: true } }),
      ),
      "Human review",
    )!;
    expect(withSoD.value).toContain("not the author");

    const plain = row(
      deriveTrustRows(manifest({ review: { human_approved: true } })),
      "Human review",
    )!;
    expect(plain.value).toBe("Human-approved");
  });

  it("assembles the data-policy line only from the asserted guarantees", () => {
    const rows = deriveTrustRows(
      manifest({ policy: { byok: true, prompts_stored: false, key_stored: false } }),
    );
    const r = row(rows, "Your data")!;
    expect(r.value).toContain("Your key is yours");
    expect(r.value).toContain("we don't store prompts");
    expect(r.value).toContain("never store your key");
  });
});

// ADR-016 D7 — the always-visible provenance lines.
describe("humanizeModel", () => {
  it("title-cases segments and dots a trailing major/minor version", () => {
    expect(humanizeModel("claude-sonnet-4-6")).toBe("Claude Sonnet 4.6");
    expect(humanizeModel("claude-opus-4-8")).toBe("Claude Opus 4.8");
  });

  it("uppercases known acronyms and tolerates unknown shapes", () => {
    expect(humanizeModel("gpt-4o")).toBe("GPT 4o");
    expect(humanizeModel("deepseek-chat")).toBe("Deepseek Chat");
  });
});

describe("identityLine (D7 LLM identity)", () => {
  it("renders human-readable provider + model", () => {
    expect(identityLine(manifest())).toBe("Anthropic (Claude) · Claude Sonnet 4.6");
  });

  it("falls back to the default provider label for an unknown provider id", () => {
    const line = identityLine(
      manifest({ provenance: { provider: "mystery", model: "x-1", model_verified: false } }),
    );
    expect(line).toContain("·"); // never throws on an unmapped provider
  });
});

describe("contentVersionLine (D7 content version)", () => {
  it("shows the generated date alone for an original generation", () => {
    expect(
      contentVersionLine(
        manifest({
          provenance: {
            provider: "anthropic",
            model: "claude-sonnet-4-6",
            model_verified: true,
            generated_at: "2026-06-14T12:00:00Z",
          },
        }),
      ),
    ).toBe("2026-06-14");
  });

  it("appends a monotonic regeneration count when the unit was regenerated", () => {
    const m = manifest({
      provenance: {
        provider: "anthropic",
        model: "claude-sonnet-4-6",
        model_verified: true,
        generated_at: "2026-06-14T12:00:00Z",
      },
    });
    expect(contentVersionLine(m, 2)).toBe("2026-06-14 · rev 2");
    expect(contentVersionLine(m, 0)).toBe("2026-06-14"); // 0 ⇒ original, no count
  });
});
