// TrustBadge — the per-artefact trust + provenance surface (ADR-015 Surface 1;
// ADR-016 D6/D7 make it the *required* provenance indicator).
//
// It only RENDERS facts the manifest already carries — it never derives or
// invents a signal, and a block the backend left unset is simply not shown (it is
// "not assessed", not a pass). Plain-language copy lives here; the facts come from
// wegofwd-llm.
//
// ADR-016 obligations:
//   D6  Provenance is visible per unit (this is the single surface — no second badge).
//   D7  LLM identity (provider · model, human-readable) and content version are
//       ALWAYS visible (collapsed); the concrete model + versions and the
//       staleness affordance live on expand. Copy is DESCRIPTIVE — it must not
//       imply the named provider verified or endorsed the content (trust-claim
//       discipline): "allow-listed model" (= on our verified-model list, ADR-012),
//       never "verified by <provider>".

import React, { useMemo, useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { colors, radius, spacing } from "@/constants/theme";
import { providerInfo } from "@/constants/providers";
import type { TrustManifest } from "@/types/trust";

type RowTone = "pass" | "note" | "info";

interface TrustRow {
  glyph: string; // ✓ / ⚠ / · — no icon-lib dependency (matches the tile-glyph idiom)
  tone: RowTone;
  label: string; // the gate, in plain language
  value: string; // the fact
}

const TONE_COLOR: Record<RowTone, string> = {
  pass: colors.success,
  note: colors.warning,
  info: colors.textSecondary,
};

const ACRONYMS: Record<string, string> = { gpt: "GPT", ai: "AI", llm: "LLM" };

// Best-effort humanised model name for D7's identity line:
// "claude-sonnet-4-6" → "Claude Sonnet 4.6". Title-cases word segments and joins
// trailing numeric segments into a dotted major.minor. The concrete raw id is
// still shown on expand, so an imperfect rendering here never hides the truth.
export function humanizeModel(id: string): string {
  const segs = id.split("-");
  const out: string[] = [];
  for (let i = 0; i < segs.length; i++) {
    const s = segs[i];
    if (/^\d+$/.test(s)) {
      let num = s;
      while (i + 1 < segs.length && /^\d+$/.test(segs[i + 1])) num += "." + segs[++i];
      if (out.length) out[out.length - 1] += ` ${num}`;
      else out.push(num);
    } else {
      out.push(ACRONYMS[s.toLowerCase()] ?? s.charAt(0).toUpperCase() + s.slice(1));
    }
  }
  return out.join(" ");
}

// Map a manifest to the expandable detail rows. Pure + exported so it can be
// unit-tested without rendering. Order = trust priority (who made it → was it
// checked → sourcing → review → integrity → policy). The collapsed identity +
// content-version lines are rendered separately (D7 "always visible").
export function deriveTrustRows(m: TrustManifest): TrustRow[] {
  const rows: TrustRow[] = [];
  const p = m.provenance;

  // An unverified (not allow-listed) model is a "note", not "info": it must
  // visibly downgrade the headline (ADR-015 AC4 — never a green pass), not sit
  // silently among the info rows. Copy is descriptive (ADR-016 D7): "allow-listed
  // model" describes OUR list, not provider endorsement of this content.
  rows.push({
    glyph: p.model_verified ? "✓" : "⚠",
    tone: p.model_verified ? "pass" : "note",
    label: "Generated by",
    value: p.model_verified ? `${p.model} · allow-listed model` : `${p.model} · unverified`,
  });

  if (m.validation) {
    const v = m.validation;
    rows.push({
      glyph: v.schema_validated ? "✓" : "⚠",
      tone: v.schema_validated ? "pass" : "note",
      label: "Structure check",
      value: v.schema_validated
        ? v.repair_attempts && v.repair_attempts > 0
          ? "Validated against our lesson template (auto-corrected)"
          : "Validated against our lesson template"
        : "Did not pass template validation",
    });
  }

  if (m.compliance) {
    const c = m.compliance;
    rows.push({
      glyph: c.status === "fail" ? "⚠" : "✓",
      tone: c.status === "pass" ? "pass" : c.status === "fail" ? "note" : "note",
      label: "Format checks",
      value: `Passed ${c.checks_passed}/${c.checks_total} format checks`,
    });
  }

  if (m.sourcing) {
    const s = m.sourcing;
    rows.push({
      glyph: s.every_claim_cited ? "✓" : "·",
      tone: s.every_claim_cited ? "pass" : "info",
      label: "Sourcing",
      value: s.every_claim_cited
        ? `Every claim cited${s.source_refs ? ` · ${s.source_refs} sources` : ""}`
        : "Partial citations",
    });
  }

  if (m.review) {
    const r = m.review;
    rows.push({
      glyph: r.human_approved ? "✓" : "·",
      tone: r.human_approved ? "pass" : "info",
      label: "Human review",
      value: r.human_approved
        ? r.approver_distinct_from_generator
          ? "Approved by a reviewer (not the author)"
          : "Human-approved"
        : "Not yet reviewed",
    });
  }

  if (m.integrity) {
    rows.push({
      glyph: "✓",
      tone: "info",
      label: "Integrity",
      value: m.integrity.signed ? "Tamper-evident · signed" : "Tamper-evident fingerprint",
    });
  }

  if (m.policy) {
    const pol = m.policy;
    const parts: string[] = [];
    if (pol.byok) parts.push("Your key is yours");
    if (!pol.prompts_stored) parts.push("we don't store prompts");
    if (!pol.key_stored) parts.push("never store your key");
    if (parts.length) {
      rows.push({ glyph: "✓", tone: "info", label: "Your data", value: parts.join(" · ") });
    }
  }

  return rows;
}

// Headline copy is descriptive only (ADR-016 D7): "Quality-checked", never
// "Verified" — the latter reads as provider endorsement of the content.
function headline(rows: TrustRow[]): { text: string; tone: RowTone } {
  if (rows.some((r) => r.tone === "note")) {
    return { text: "Quality-checked (with notes)", tone: "note" };
  }
  return { text: "Quality-checked", tone: "pass" };
}

// D7 identity line: provider + model, human-readable. Provider label comes from
// the existing BYOK provider registry; model is humanised.
export function identityLine(m: TrustManifest): string {
  const p = m.provenance;
  return `${providerInfo(p.provider).label} · ${humanizeModel(p.model)}`;
}

// D7 content version line: generated date + monotonic regeneration count. The
// count is book/topic metadata (book.ts revisionHistory), not in the manifest, so
// the host passes it; absent ⇒ show the date alone.
export function contentVersionLine(m: TrustManifest, revisionCount?: number): string {
  const parts: string[] = [];
  const at = m.provenance.generated_at;
  if (at) parts.push(at.slice(0, 10));
  if (typeof revisionCount === "number" && revisionCount > 0) parts.push(`rev ${revisionCount}`);
  return parts.join(" · ");
}

interface TrustBadgeProps {
  manifest: TrustManifest;
  /** Start expanded (e.g. on a dedicated "trust" screen). Default: collapsed. */
  defaultExpanded?: boolean;
  /**
   * Monotonic regeneration count for this unit (ADR-016 D7 content version,
   * from book.ts revisionHistory). 0/undefined ⇒ original generation.
   */
  revisionCount?: number;
  /**
   * The host compares the unit's model/integration_version against the registry
   * default (ADR-012/016 D7 staleness) and passes true when this content was made
   * with an older model. The badge only renders the quiet "regenerate?" hint — it
   * never reaches the registry itself.
   */
  isStale?: boolean;
}

export function TrustBadge({
  manifest,
  defaultExpanded = false,
  revisionCount,
  isStale = false,
}: TrustBadgeProps) {
  const [expanded, setExpanded] = useState(defaultExpanded);
  const rows = useMemo(() => deriveTrustRows(manifest), [manifest]);
  const head = useMemo(() => headline(rows), [rows]);
  const identity = useMemo(() => identityLine(manifest), [manifest]);
  const version = useMemo(
    () => contentVersionLine(manifest, revisionCount),
    [manifest, revisionCount],
  );
  const p = manifest.provenance;

  return (
    <View style={styles.card}>
      <Pressable
        onPress={() => setExpanded((e) => !e)}
        accessibilityRole="button"
        accessibilityLabel={`Content trust: ${head.text}. Generated by ${identity}${
          version ? `, ${version}` : ""
        }. ${expanded ? "Collapse" : "Expand"} details.`}
        style={styles.header}
      >
        <Text style={[styles.shield, { color: TONE_COLOR[head.tone] }]}>◈</Text>
        {/* Always-visible block: headline + LLM identity + content version (D7) */}
        <View style={styles.headText}>
          <Text style={styles.headTitle}>{head.text}</Text>
          <Text style={styles.identity}>{identity}</Text>
          {version ? <Text style={styles.version}>{version}</Text> : null}
        </View>
        <Text style={styles.chevron}>{expanded ? "▾" : "▸"}</Text>
      </Pressable>

      {/* Staleness affordance (D7) — quiet, always visible so the user can act
          without expanding. */}
      {isStale ? (
        <Text style={styles.stale}>Made with an older model — regenerate?</Text>
      ) : null}

      {expanded && (
        <View style={styles.body}>
          {rows.map((r, i) => (
            <View key={i} style={styles.row}>
              <Text style={[styles.glyph, { color: TONE_COLOR[r.tone] }]}>{r.glyph}</Text>
              <View style={styles.rowText}>
                <Text style={styles.rowLabel}>{r.label}</Text>
                <Text style={styles.rowValue}>{r.value}</Text>
              </View>
            </View>
          ))}
          <Text style={styles.footnote}>
            How this content was produced and checked.
            {p.integration_version ? ` Engine v${p.integration_version}` : ""}
            {p.contract_version ? ` · contract v${p.contract_version}` : ""}
          </Text>
        </View>
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  card: {
    backgroundColor: colors.surface,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: "hidden",
  },
  header: {
    flexDirection: "row",
    alignItems: "flex-start",
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    gap: spacing.sm,
  },
  shield: { fontSize: 16, marginTop: 1 },
  headText: { flex: 1 },
  headTitle: { color: colors.text, fontSize: 14, fontWeight: "600" },
  identity: { color: colors.textSecondary, fontSize: 12, marginTop: 1 },
  version: { color: colors.textMuted, fontSize: 11, marginTop: 1 },
  chevron: { color: colors.textMuted, fontSize: 12, marginTop: 2 },
  stale: {
    color: colors.warning,
    fontSize: 12,
    paddingHorizontal: spacing.md,
    paddingBottom: spacing.sm,
  },
  body: {
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    gap: spacing.sm,
  },
  row: { flexDirection: "row", alignItems: "flex-start", gap: spacing.sm },
  glyph: { fontSize: 14, width: 16, textAlign: "center", marginTop: 1 },
  rowText: { flex: 1 },
  rowLabel: { color: colors.textSecondary, fontSize: 11, textTransform: "uppercase", letterSpacing: 0.4 },
  rowValue: { color: colors.text, fontSize: 13 },
  footnote: {
    color: colors.textMuted,
    fontSize: 11,
    marginTop: spacing.xs,
    paddingTop: spacing.sm,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
});
